### PR TITLE
Adding components root and empty workspace config

### PR DESCRIPTION
**Pull request by nciric**
Going with the assumption that we'll use workspaces for this project. Detailed explanation of workspace approach (benefits and drawbacks) can be found in [official docs](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html).

For example, all crates in a workspace have the same dependency versions, and all of the build outputs are in the same folder.

This is related to issue #18

### CODE REVIEW

**Comment by Manishearth** [comment]
Wait, the cargo.toml should probably be at the top level.

**Comment by nciric** [comment]
> Wait, the cargo.toml should probably be at the top level.

But it is - at the top of components. Do you think it should be in the root of the repository?
I thought all of the Rust code would go under components, and none directly under root.

**Comment by nciric** [comment]
> > Wait, the cargo.toml should probably be at the top level.
> 
> But it is - at the top of components. Do you think it should be in the root of the repository?
> I thought all of the Rust code would go under components, and none directly under root.

Ah, you probably think that components won't be the only top folder - for example wrappers can be another, but they are all related in one workspace. In that case it makes sense.

**Comment by Manishearth** [comment]
Yeah there's very little reason to have multiple workspaces in a repo

**Comment by nciric** [comment]
> Yeah there's very little reason to have multiple workspaces in a repo

Done, PTAL

**Pull request merged**
